### ISSUE TITLE
uninitialized constant Kaminari::Mongoid::VERSION (NameError)

### ISSUE THREAD

**Issue by selcham** [kaminari/kaminari-mongoid#2]
I just moved from 0.16.x to the last github version in order to have the new `params_on_first_page` config.

I use the last versions from https://github.com/amatsuda/kaminari and  https://github.com/kaminari/kaminari-mongoid and got this error on server start:

```
....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid/mongoid_extension.rb:24:in `<module:Document>': uninitialized constant Kaminari::Mongoid::VERSION (NameError)
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid/mongoid_extension.rb:6:in `<module:MongoidExtension>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid/mongoid_extension.rb:5:in `<module:Mongoid>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid/mongoid_extension.rb:4:in `<module:Kaminari>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid/mongoid_extension.rb:3:in `<top (required)>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid.rb:3:in `require'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/kaminari-mongoid-0.1.1/lib/kaminari/mongoid.rb:3:in `<top (required)>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:100:in `require'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:100:in `rescue in block in require'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:77:in `block in require'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
	from ......config/application.rb:17:in `<top (required)>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from .../...bin/rails:8:in `require'
	from ......bin/rails:8:in `<top (required)>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
	from ....rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from ....rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ....rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from .../...bin/spring:13:in `<top (required)>'
	from .../...bin/rails:3:in `load'
	from .../...bin/rails:3:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

Thanks

**Comment by yuki24** [comment]
Do you have `gem 'mongoid'` in your Gemfile?

**Comment by selcham** [comment]
Yes, I'm using mongoid 5.1.1
